version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py makemigrations cinema &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cinema_db
      - POSTGRES_USER=cinema_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  postgres_data: